version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./front-end
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend

  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    depends_on:
      - db_mysql
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - HOSTNAME=db_mysql
      - MYSQL_HOST=db_mysql
      - MYSQL_PORT=3306

  db_mysql:
    image: mysql:8.0.21
    container_name: db_mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'